### ISSUE TITLE
OSX and windows binary can't access lib2to3 Grammar.txt

### ISSUE THREAD

**Issue by littleskunk** [Storj/storjnode#102]

**Comment by littleskunk** [comment]
storjnode.exe
Traceback (most recent call last):
  File "storjnode", line 12, in <module>
  File "storjnode__init__.pyo", line 3, in <module>
  File "storjnode\network__init__.pyo", line 1, in <module>
  File "storjnode\network\node.pyo", line 12, in <module>
  File "storjnode\network\server.pyo", line 12, in <module>
  File "storjkademlia\network.pyo", line 14, in <module>
  File "storjkademlia\protocol.pyo", line 5, in <module>
  File "past__init__.pyo", line 88, in <module>
  File "past\translation__init__.pyo", line 42, in <module>
  File "lib2to3\refactor.pyo", line 27, in <module>
  File "lib2to3\fixer_util.pyo", line 9, in <module>
  File "lib2to3\pygram.pyo", line 32, in <module>
  File "lib2to3\pgen2\driver.pyo", line 121, in load_grammar
  File "lib2to3\pgen2\pgen.pyo", line 385, in generate_grammar
  File "lib2to3\pgen2\pgen.pyo", line 15, in **init**
IOError: [Errno 2] No such file or directory: 'C:\Users\Skunk\Downloads\storjnode\library.zip\lib2to3\Grammar.txt'

Grammar.txt exists in library.zip files. Same problem with the osx binary.

**Comment by littleskunk** [comment]
Open lib2to3 issue: https://bugs.python.org/issue24960

**Comment by littleskunk** [comment]
py2exe has a skip_archive option as workaround. This is no solution. It is only a temporary fix to be able to run the binary again.

The workaround is not working for py2app.

**Comment by robertsdotpm** [comment]
Maybe cx_freeze would work?

**Comment by littleskunk** [comment]
Same problem with cx_freeze: http://stackoverflow.com/questions/32422745/problems-with-cx-freeze-and-networkx

But maybe it will work as workaround for osx.

**Comment by littleskunk** [comment]
I did a manual test on osx. Unzip side-package.zip and replace it with a folder (same name). I can now execute the binary on osx. The farm command was working as well. I don't have a problem with the osx workaround. Everything is still inside storjnode.app.

**Comment by littleskunk** [comment]
OSX fixed with https://github.com/Storj/autobin/commit/b813ce20c880bc1e49d03e6e599c747686a3ebc5
