### ISSUE TITLE
Bandwidth test failed, store path limit reached, endless loop Test already in progress

### ISSUE THREAD

**Issue by littleskunk** [Storj/storjnode#105]
Tested with https://ci.appveyor.com/project/Storj/storjnode/build/job/pad1kklvaxjd6aks/artifacts
80GB free on Drive C.

```
D:\storjnode>storjnode.exe --wallet xprv9s21ZrQH143K3m4QEqqF2hkQvTHczjeQbebVprErgQLF684MzDmbpMRDN4YdaTC9fxAFmw8sSKh6FqDXQYVZukmRgLhuYSbcTFca16Ut3EV farm
2016-02-14 09:04:51,246 INFO storjnode.network.node 124: Started storjnode on port 61894 with address 1Gw99SmF9C1J8jLHHUQum4MMXeuB9kz78V
refreshing peers
refreshing peers
refreshing peers
2016-02-14 09:08:51,266 INFO storjnode.api 119: Enabling monitor responses.
2016-02-14 09:08:51,273 INFO storjnode.api 127: Starting monitor crawler.
2016-02-14 09:08:52,420 INFO storjnode.network.monitor 527: Crawling dataset 0
2016-02-14 09:08:52,530 INFO storjnode.network.monitor 229: Requesting info/peers for 13VT1RexLErkT6sKCi21xGkHUYxt5p7oUT, try 0!
2016-02-14 09:08:52,548 INFO storjnode.network.monitor 235: Requesting peers/neighbours from 13VT1RexLErkT6sKCi21xGkHUYxt5p7oUT!
2016-02-14 09:08:53,403 INFO storjnode.network.monitor 244: Requesting info from 13VT1RexLErkT6sKCi21xGkHUYxt5p7oUT!
2016-02-14 09:08:55,096 INFO storjnode.network.monitor 229: Requesting info/peers for 1Ca5ZxbDHZWCKGcDzxPEN2eNfkbRkS1bB3, try 0!
2016-02-14 09:08:55,108 INFO storjnode.network.monitor 235: Requesting peers/neighbours from 1Ca5ZxbDHZWCKGcDzxPEN2eNfkbRkS1bB3!
2016-02-14 09:08:55,877 INFO storjnode.network.monitor 244: Requesting info from 1Ca5ZxbDHZWCKGcDzxPEN2eNfkbRkS1bB3!
2016-02-14 09:08:58,473 INFO storjnode.network.monitor 229: Requesting info/peers for 1PgRQYYwJsFeqEiEJwhVYEKx9z96rfepW8, try 0!
2016-02-14 09:08:58,490 INFO storjnode.network.monitor 235: Requesting peers/neighbours from 1PgRQYYwJsFeqEiEJwhVYEKx9z96rfepW8!
2016-02-14 09:09:01,476 INFO storjnode.network.monitor 244: Requesting info from 1PgRQYYwJsFeqEiEJwhVYEKx9z96rfepW8!
2016-02-14 09:09:03,861 INFO storjnode.network.monitor 111: Received peers from 1Ca5ZxbDHZWCKGcDzxPEN2eNfkbRkS1bB3!
2016-02-14 09:09:05,381 INFO storjnode.network.monitor 133: Received info from 1Ca5ZxbDHZWCKGcDzxPEN2eNfkbRkS1bB3!
2016-02-14 09:09:05,390 INFO storjnode.network.monitor 167: Moving 1Ca5ZxbDHZWCKGcDzxPEN2eNfkbRkS1bB3 to scanned
2016-02-14 09:09:05,398 INFO storjnode.network.monitor 178: Scan complete for 1Ca5ZxbDHZWCKGcDzxPEN2eNfkbRkS1bB3, scanned:1, scanning:2, processed:1!
2016-02-14 09:09:05,480 INFO storjnode.network.monitor 326: Starting bandwidth test for: 1Ca5ZxbDHZWCKGcDzxPEN2eNfkbRkS1bB3
2016-02-14 09:09:16,322 INFO storjnode.network.monitor 111: Received peers from 1PgRQYYwJsFeqEiEJwhVYEKx9z96rfepW8!
2016-02-14 09:09:17,891 INFO storjnode.network.monitor 133: Received info from 1PgRQYYwJsFeqEiEJwhVYEKx9z96rfepW8!
2016-02-14 09:09:17,900 INFO storjnode.network.monitor 167: Moving 1PgRQYYwJsFeqEiEJwhVYEKx9z96rfepW8 to scanned
2016-02-14 09:09:17,907 INFO storjnode.network.monitor 178: Scan complete for 1PgRQYYwJsFeqEiEJwhVYEKx9z96rfepW8, scanned:1, scanning:1, processed:1!
2016-02-14 09:09:21,400 WARNING storjnode.storage.manager 187: Store path limit reached for C:\Users\jensh_000\.storj\store cannot add 628bc20593b278054a6677415242ba0396d9d3f530b749b1d3be1d699b9aa051: Required 1048576 > 1032779 free.
2016-02-14 09:09:21,417 ERROR storjnode.network.monitor 255: Bandwidth test failed: <twisted.python.failure.Failure exceptions.MemoryError: Not enough space to add 628bc20593b278054a6677415242ba0396d9d3f530b749b1d3be1d699b9aa051!>
2016-02-14 09:09:21,484 INFO storjnode.network.monitor 321: Skipping: They will do the bandwidth test
2016-02-14 09:09:21,596 INFO storjnode.network.monitor 326: Starting bandwidth test for: 1Ca5ZxbDHZWCKGcDzxPEN2eNfkbRkS1bB3
2016-02-14 09:09:32,196 ERROR storjnode.network.monitor 255: Bandwidth test failed: <twisted.python.failure.Failure exceptions.Exception: Test already in progress>
2016-02-14 09:09:32,250 INFO storjnode.network.monitor 326: Starting bandwidth test for: 1Ca5ZxbDHZWCKGcDzxPEN2eNfkbRkS1bB3
2016-02-14 09:09:39,631 ERROR storjnode.network.monitor 255: Bandwidth test failed: <twisted.python.failure.Failure exceptions.Exception: Test already in progress>
2016-02-14 09:09:39,721 INFO storjnode.network.monitor 326: Starting bandwidth test for: 1Ca5ZxbDHZWCKGcDzxPEN2eNfkbRkS1bB3
2016-02-14 09:09:52,256 ERROR storjnode.network.monitor 255: Bandwidth test failed: <twisted.python.failure.Failure exceptions.Exception: Test already in progress>
2016-02-14 09:09:52,351 INFO storjnode.network.monitor 326: Starting bandwidth test for: 1Ca5ZxbDHZWCKGcDzxPEN2eNfkbRkS1bB3
2016-02-14 09:10:02,142 INFO storjnode.network.monitor 229: Requesting info/peers for 13VT1RexLErkT6sKCi21xGkHUYxt5p7oUT, try 1!
2016-02-14 09:10:02,161 INFO storjnode.network.monitor 235: Requesting peers/neighbours from 13VT1RexLErkT6sKCi21xGkHUYxt5p7oUT!
2016-02-14 09:10:04,440 INFO storjnode.network.monitor 244: Requesting info from 13VT1RexLErkT6sKCi21xGkHUYxt5p7oUT!
2016-02-14 09:10:06,206 ERROR storjnode.network.monitor 255: Bandwidth test failed: <twisted.python.failure.Failure exceptions.Exception: Test already in progress>
2016-02-14 09:10:06,306 INFO storjnode.network.monitor 326: Starting bandwidth test for: 1Ca5ZxbDHZWCKGcDzxPEN2eNfkbRkS1bB3
2016-02-14 09:10:11,831 ERROR storjnode.network.monitor 255: Bandwidth test failed: <twisted.python.failure.Failure exceptions.Exception: Test already in progress>
2016-02-14 09:10:11,895 INFO storjnode.network.monitor 326: Starting bandwidth test for: 1Ca5ZxbDHZWCKGcDzxPEN2eNfkbRkS1bB3
2016-02-14 09:10:16,262 ERROR storjnode.network.monitor 255: Bandwidth test failed: <twisted.python.failure.Failure exceptions.Exception: Test already in progress>
2016-02-14 09:10:16,345 INFO storjnode.network.monitor 326: Starting bandwidth test for: 1Ca5ZxbDHZWCKGcDzxPEN2eNfkbRkS1bB3
2016-02-14 09:10:28,894 ERROR storjnode.network.monitor 255: Bandwidth test failed: <twisted.python.failure.Failure exceptions.Exception: Test already in progress>
2016-02-14 09:10:39,365 INFO storjnode.network.monitor 326: Starting bandwidth test for: 1Ca5ZxbDHZWCKGcDzxPEN2eNfkbRkS1bB3
2016-02-14 09:10:41,250 INFO storjnode.network.monitor 510: Stopping monitor!
2016-02-14 09:10:47,036 INFO storjnode.network.monitor 378: MONITOR POST CRAWL STATISTICS: {
  "successfully_processed": 1,
  "testing_bandwidth": true,
  "waiting_for_bandwidth_test": 0,
  "scanning_info_and_peers": 1
}
2016-02-14 09:10:48,561 INFO storjnode.network.monitor 545: Saved dataset 0 as shard d01211766313ce3d05bd2fb8fc34c45af61a31aff62708d10599a23a846bcb53
2016-02-14 09:10:48,579 INFO storjnode.network.monitor 557: Added DHT entry monitor_dataset_1Gw99SmF9C1J8jLHHUQum4MMXeuB9kz78V_0 => d01211766313ce3d05bd2fb8fc34c45af61a31aff62708d10599a23a846bcb53
2016-02-14 09:10:48,601 INFO storjnode.api 176: Crawl complete, d01211766313ce3d05bd2fb8fc34c45af61a31aff62708d10599a23a846bcb53 published at monitor_dataset_1Gw99SmF9C1J8jLHHUQum4MMXeuB9kz78V_0
2016-02-14 09:10:48,680 ERROR storjnode.network.monitor 255: Bandwidth test failed: <twisted.python.failure.Failure exceptions.Exception: Test already in progress>
Traceback (most recent call last):
  File "storjnode", line 22, in <module>
  File "apigen\apigen.pyo", line 254, in run

  File "apigen\apigen.pyo", line 58, in wrapper

  File "storjnode\api.pyo", line 233, in farm

  File "pyp2p\net.pyo", line 815, in stop

Exception: Process was interrupted.
```

**Comment by littleskunk** [comment]
Problem 1.
Free space calculation is wrong.

https://github.com/Storj/storjnode/blob/develop/storjnode/storage/manager.py#L184<

```
free = limit - used
```

The limit is 1MB. After some days 1 MB is used with datasets and bandwidthtest results.

Problem 1.
https://github.com/Storj/storjnode/blob/develop/storjnode/storage/manager.py#L1

```
used = storjnode.util.get_folder_size(store_path)
```

Lets use the root of drive C as store path. Im my case 30GB used. Storjnode will always fail with a nice exception. (Did not try it. Maybe I am wrong. Will check that later.)

Problem 2.
https://github.com/Storj/storjnode/blob/develop/storjnode/network/bandwidth/test.py#L336
manager.add throws an exception but the bandwidth test doen't call his reset method.

Sorry I am at vacation this week and can't offer you a pull request.

**Comment by littleskunk** [comment]
Problem 1.
https://github.com/Storj/storjnode/blob/develop/storjnode/storage/manager.py#L1
```
used = storjnode.util.get_folder_size(store_path)
```
Lets use the root of drive C as store path. Im my case 30GB used. Storjnode will always fail with a nice exception. (Did not try it. Maybe I am wrong. Will check that later.)

**Comment by littleskunk** [comment]
Problem 2.
https://github.com/Storj/storjnode/blob/develop/storjnode/network/bandwidth/test.py#L336
manager.add throws an exception but the bandwidth test doen't call his reset method.

Sorry I am at vacation this week and can't offer you a pull request.

**Comment by robertsdotpm** [comment]
Really nice finds. I'll try fix them first thing today

**Comment by robertsdotpm** [comment]
What are the results of cat ~/.storj/cfg.json | grep limit for you @littleskunk

**Comment by littleskunk** [comment]
Yes i found the place where i could set a higher limit. It was set to 1M (default maybe from an old storjnode version). Works as expected. The error message confused me.
Required 1048576 > 1032779 free.
I would expect: (Store path) Limit 1048576 < XXX used.

**Comment by robertsdotpm** [comment]
Should be fixed now.

**Comment by littleskunk** [comment]
Retest with a store limit of 1 byte passed but now the bandwidt test restarts all the time. It is still a endless loop.

`2016-02-22 10:08:09,457 WARNING storjnode.storage.manager 189: Store path limit reached for C:\Users\jensh_000\.storj\store cannot add 0c29d78f383c96185b92b6e7623036ed6f832d8d04612d633af29cedc8d5c403: Required 1048576 > 1 free.
2016-02-22 10:08:09,476 INFO storjnode.network.monitor 271: Bandwidth test successfull: None
2016-02-22 10:08:09,480 ERROR storjnode.network.monitor 299: No test results for success callback
2016-02-22 10:08:09,484 ERROR storjnode.network.monitor 257: Bandwidth test failed: <twisted.python.failure.Failure exceptions.Exception: Bandwidth test none results>
2016-02-22 10:08:09,509 INFO storjnode.network.monitor 330: Starting bandwidth test for: 1Ca5ZxbDHZWCKGcDzxPEN2eNfkbRkS1bB3
2016-02-22 10:08:22,289 WARNING storjnode.storage.manager 189: Store path limit reached for C:\Users\jensh_000\.storj\store cannot add 36ccae2f8396e86ed28ec787682e205d6a0f9714f9126ed49d4de6638d2c33d6: Required 1048576 > 1 free.
2016-02-22 10:08:22,305 INFO storjnode.network.monitor 271: Bandwidth test successfull: None
2016-02-22 10:08:22,309 ERROR storjnode.network.monitor 299: No test results for success callback
2016-02-22 10:08:22,312 ERROR storjnode.network.monitor 257: Bandwidth test failed: <twisted.python.failure.Failure exceptions.Exception: Bandwidth test none results>
2016-02-22 10:08:22,335 INFO storjnode.network.monitor 330: Starting bandwidth test for: 1Cv8qQyppoUBHtcm5vzE2u4o5EQ6eYf88p
2016-02-22 10:08:27,367 WARNING storjnode.storage.manager 189: Store path limit reached for C:\Users\jensh_000\.storj\store cannot add b24f2ddde7ce1833978b971c8c7b2ce28f00d27530c329374e9812e6fb6494bc: Required 1048576 > 1 free.
2016-02-22 10:08:27,382 INFO storjnode.network.monitor 271: Bandwidth test successfull: None
2016-02-22 10:08:27,388 ERROR storjnode.network.monitor 299: No test results for success callback
2016-02-22 10:08:27,391 ERROR storjnode.network.monitor 257: Bandwidth test failed: <twisted.python.failure.Failure exceptions.Exception: Bandwidth test none results>
2016-02-22 10:08:27,470 INFO storjnode.network.monitor 330: Starting bandwidth test for: 1GB6M5FYBZf75zuQFqcvbvaNMLZTazrD1P
2016-02-22 10:08:37,165 INFO storjnode.network.monitor 231: Requesting info/peers for 1MsZFgEKc8u24jpPFe5gGDCSb8Beos8zL9, try 1!
2016-02-22 10:08:37,173 INFO storjnode.network.monitor 237: Requesting peers/neighbours from 1MsZFgEKc8u24jpPFe5gGDCSb8Beos8zL9!
2016-02-22 10:08:40,917 WARNING storjnode.storage.manager 189: Store path limit reached for C:\Users\jensh_000\.storj\store cannot add b69fc2f72d3f128a25f965abbef5d0713a54ba77fa13fa5a477393fee16ed55d: Required 1048576 > 1 free.
2016-02-22 10:08:41,055 INFO storjnode.network.monitor 246: Requesting info from 1MsZFgEKc8u24jpPFe5gGDCSb8Beos8zL9!
2016-02-22 10:08:41,585 INFO storjnode.network.monitor 231: Requesting info/peers for 1AbWduKu24tqckGL9QRHdSQ5pm8SFoE4Yb, try 1!
2016-02-22 10:08:41,594 INFO storjnode.network.monitor 237: Requesting peers/neighbours from 1AbWduKu24tqckGL9QRHdSQ5pm8SFoE4Yb!
2016-02-22 10:08:42,479 INFO storjnode.network.monitor 246: Requesting info from 1AbWduKu24tqckGL9QRHdSQ5pm8SFoE4Yb!
2016-02-22 10:08:43,263 INFO storjnode.network.monitor 271: Bandwidth test successfull: None
2016-02-22 10:08:43,266 ERROR storjnode.network.monitor 299: No test results for success callback
2016-02-22 10:08:43,270 ERROR storjnode.network.monitor 257: Bandwidth test failed: <twisted.python.failure.Failure exceptions.Exception: Bandwidth test none results>
2016-02-22 10:08:43,364 INFO storjnode.network.monitor 330: Starting bandwidth test for: 1PgRQYYwJsFeqEiEJwhVYEKx9z96rfepW8
2016-02-22 10:08:52,562 INFO storjnode.network.monitor 231: Requesting info/peers for 1DKzcJbys3N8DxAK5iZtHPnAG3VCf4xtEH, try 1!
2016-02-22 10:08:52,581 INFO storjnode.network.monitor 237: Requesting peers/neighbours from 1DKzcJbys3N8DxAK5iZtHPnAG3VCf4xtEH!
2016-02-22 10:08:55,453 INFO storjnode.network.monitor 246: Requesting info from 1DKzcJbys3N8DxAK5iZtHPnAG3VCf4xtEH!
2016-02-22 10:08:56,631 WARNING storjnode.storage.manager 189: Store path limit reached for C:\Users\jensh_000\.storj\store cannot add 598f731e2c9d927417a5a0b21138f85395076abcb100de2405b8512b9ede122a: Required 1048576 > 1 free.
2016-02-22 10:08:57,888 INFO storjnode.network.monitor 231: Requesting info/peers for 1KxP3AozDqJcJXDjR1MGGRDx9MbLTYtnZF, try 1!
2016-02-22 10:08:57,894 INFO storjnode.network.monitor 237: Requesting peers/neighbours from 1KxP3AozDqJcJXDjR1MGGRDx9MbLTYtnZF!
2016-02-22 10:08:58,421 INFO storjnode.network.monitor 246: Requesting info from 1KxP3AozDqJcJXDjR1MGGRDx9MbLTYtnZF!
2016-02-22 10:08:59,094 INFO storjnode.network.monitor 514: Stopping monitor!
2016-02-22 10:08:59,552 INFO storjnode.network.monitor 271: Bandwidth test successfull: None`

What is the expected behavior if there is no space available to save the bandwidth test data?

BTW: Ignore problem 1. That was a user error. Everything fine with the storage manager.
