### ISSUE TITLE
Crawler exception

### ISSUE THREAD

**Issue by littleskunk** [Storj/storjnode#107]
Exception storjnode farm
https://ci.appveyor.com/project/Storj/storjnode/build/job/3kvtrecj8kk0hmdk/artifacts

```
storjnode.exe --wallet xprv9s21ZrQH143K3m4QEqqF2hkQvTHczjeQbebVprErgQLF684MzDmbpMRDN4YdaTC9fxAFmw8sSKh6FqDXQYVZukmRgLhuYSbcTFca16Ut3EV farm
2016-02-18 17:17:56,249 INFO storjnode.network.node 131: Started storjnode on port 49378 with address 1Gw99SmF9C1J8jLHHUQum4MMXeuB9kz78V
refreshing peers
refreshing peers
refreshing peers
2016-02-18 17:21:56,270 INFO storjnode.api 119: Enabling monitor responses.
2016-02-18 17:21:56,279 INFO storjnode.api 127: Starting monitor crawler.
Traceback (most recent call last):
  File "storjnode", line 22, in <module>
  File "apigen\apigen.pyo", line 254, in run

  File "apigen\apigen.pyo", line 58, in wrapper

  File "storjnode\api.pyo", line 224, in farm

  File "storjnode\api.pyo", line 130, in _init_monitor

  File "storjnode\network\monitor.pyo", line 509, in __init__

  File "storjnode\network\monitor.pyo", line 442, in find_next_free_dataset_num

  File "storjnode\network\monitor.pyo", line 435, in _get_value

  File "storjnode\network\node.pyo", line 797, in __getitem__

  File "crochet\_eventloop.pyo", line 461, in wrapper

  File "crochet\_eventloop.pyo", line 231, in wait

  File "twisted\internet\defer.pyo", line 588, in _runCallbacks

  File "storjkademlia\crawling.pyo", line 93, in _nodesFound

  File "storjkademlia\crawling.pyo", line 173, in happened

AttributeError: Failure instance has no attribute '__getitem__'
```

**Comment by F483** [comment]
This seems to be cause by an unhanded failure case. I fixed it and it should no longer be a problem.

See https://github.com/Storj/storjkademlia/commit/f1062e4f42aaa5f8f8c76318a38be557d77d55dc
