### ISSUE TITLE
get_fs_type throws exception

### ISSUE THREAD

**Issue by littleskunk** [Storj/storjnode#111]
Same exception and same solution like https://github.com/Storj/dataserv-client/issues/140

**Comment by littleskunk** [comment]
Sorry I must be blind. The exception is different:

brandon [01:12] 

```
dataserv-client --debug register 
/usr/lib64/python2.7/site-packages/psutil/_pslinux.py:154: RuntimeWarning: couldn't determine platform's TOTAL_PHYMEM
  warnings.warn("couldn't determine platform's TOTAL_PHYMEM", RuntimeWarning)
2016-02-28 18:55:32,275 ERROR dataserv_client.cli 251: 'module' object has no attribute 'get_disk_partitions'
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/dataserv_client/cli.py", line 242, in main
    nop2p=arguments.pop("nop2p"),
  File "/usr/lib/python2.7/site-packages/dataserv_client/api.py", line 68, in __init__
    fstype = storjnode.util.get_fs_type(self.store_path)
  File "/usr/lib/python2.7/site-packages/storjnode/util.py", line 213, in get_fs_type
    for partition in psutil.disk_partitions():
  File "/usr/lib64/python2.7/site-packages/psutil/__init__.py", line 1451, in disk_partitions
    return _psplatform.disk_partitions(all)
  File "/usr/lib64/python2.7/site-packages/psutil/_pslinux.py", line 321, in disk_partitions
    partitions = _psutil_linux.get_disk_partitions()
AttributeError: 'module' object has no attribute 'get_disk_partitions'
Traceback (most recent call last):
  File "/usr/bin/dataserv-client", line 10, in <module>
    cli.main(sys.argv[1:])
  File "/usr/lib/python2.7/site-packages/dataserv_client/cli.py", line 252, in main
    raise e
AttributeError: 'module' object has no attribute 'get_disk_partitions'
```

**Comment by littleskunk** [comment]
Problem solved. psutil 1.2.1...

```
pip install --upgrade dataserv-client 
Requirement already up-to-date: partialhash>=1.1.0 in /usr/lib/python2.7/site-packages (from dataserv-client)
Requirement already up-to-date: storjcore>=0.0.6 in /usr/lib/python2.7/site-packages (from dataserv-client)
Requirement already up-to-date: future>=0.15.0 in /usr/lib/python2.7/site-packages (from dataserv-client)
Requirement already up-to-date: RandomIO>=0.2.1 in /usr/lib/python2.7/site-packages (from dataserv-client)
Requirement already up-to-date: storjnode>=0.0.18 in /usr/lib/python2.7/site-packages (from dataserv-client)
Collecting psutil>=3.2.2 (from dataserv-client)
  Using cached psutil-4.0.0.tar.gz
Collecting pycoin>=0.52 (from btctxstore>=4.6.0->dataserv-client)
  Using cached pycoin-0.62.tar.gz
Collecting six>=1.10.0 (from btctxstore>=4.6.0->dataserv-client)
  Using cached six-1.10.0-py2.py3-none-any.whl
Requirement already up-to-date: ecdsa>=0.13 in /usr/lib/python2.7/site-packages (from btctxstore>=4.6.0->dataserv-client)
Requirement already up-to-date: pycrypto>=2.6.1 in /usr/lib64/python2.7/site-packages (from storjcore>=0.0.6->dataserv-client)
Requirement already up-to-date: crochet>=1.4.0 in /usr/lib/python2.7/site-packages (from storjnode>=0.0.18->dataserv-client)
Requirement already up-to-date: netifaces>=0.10.4 in /usr/lib64/python2.7/site-packages (from storjnode>=0.0.18->dataserv-client)
Requirement already up-to-date: twisted>=15.4.0 in /usr/lib64/python2.7/site-packages (from storjnode>=0.0.18->dataserv-client)
Requirement already up-to-date: pyp2p>=0.4.5 in /usr/lib/python2.7/site-packages (from storjnode>=0.0.18->dataserv-client)
Requirement already up-to-date: ipaddress>=1.0.14 in /usr/lib/python2.7/site-packages (from storjnode>=0.0.18->dataserv-client)
Requirement already up-to-date: kademlia>=0.5 in /usr/lib/python2.7/site-packages (from storjnode>=0.0.18->dataserv-client)
Requirement already up-to-date: requests>=2.8.1 in /usr/lib/python2.7/site-packages (from storjnode>=0.0.18->dataserv-client)
Requirement already up-to-date: ntplib>=0.3.3 in /usr/lib/python2.7/site-packages (from storjnode>=0.0.18->dataserv-client)
Requirement already up-to-date: zope.interface>=3.6.0 in /usr/lib64/python2.7/site-packages (from twisted>=15.4.0->storjnode>=0.0.18->dataserv-client)
Requirement already up-to-date: pyroute2>=0.3.15 in /usr/lib/python2.7/site-packages (from pyp2p>=0.4.5->storjnode>=0.0.18->dataserv-client)
Requirement already up-to-date: rpcudp>=1.0 in /usr/lib/python2.7/site-packages (from kademlia>=0.5->storjnode>=0.0.18->dataserv-client)
Requirement already up-to-date: setuptools in /usr/lib/python2.7/site-packages (from zope.interface>=3.6.0->twisted>=15.4.0->storjnode>=0.0.18->dataserv-client)
Requirement already up-to-date: u-msgpack-python>=1.5 in /usr/lib/python2.7/site-packages (from rpcudp>=1.0->kademlia>=0.5->storjnode>=0.0.18->dataserv-client)
Installing collected packages: pycoin, six, btctxstore, psutil
  Found existing installation: pycoin 0.52
    Uninstalling pycoin-0.52:
      Successfully uninstalled pycoin-0.52
  Running setup.py install for pycoin
  Found existing installation: six 1.9.0
    Uninstalling six-1.9.0:
      Successfully uninstalled six-1.9.0
  Found existing installation: btctxstore 4.6.0
    Uninstalling btctxstore-4.6.0:
      Successfully uninstalled btctxstore-4.6.0
  Running setup.py install for btctxstore
  Found existing installation: psutil 1.2.1
    DEPRECATION: Uninstalling a distutils installed project (psutil) has been deprecated and will be removed in a future version. This is due to the fact that uninstalling a distutils project will only partially uninstall the project.
    Uninstalling psutil-1.2.1:
      Successfully uninstalled psutil-1.2.1
  Running setup.py install for psutil
Successfully installed btctxstore-4.6.1 psutil-4.0.0 pycoin-0.62 six-1.10.0
```
