### ISSUE TITLE
Random Error Output on Version

### ISSUE THREAD

**Issue by super3** [Storj/storjnode#14]
[project:sm]

```
C:\Users\super3\Desktop\storjnode-0.0.7.win32>storjnode.exe version
v0.0.7
Traceback (most recent call last):
  File "storjnode", line 10, in <module>
  File "storjnode\cli.pyo", line 168, in main
NameError: global name 'exit' is not defined
```

**Comment by littleskunk** [comment]
Uploaded a new v0.0.7 with local hotfix. Its only a hotfix. If we have to build v0.0.7 again the bug can come again.

Final bugfix will be in the next version.
