### ISSUE TITLE
Freeze after exception

### ISSUE THREAD

**Issue by littleskunk** [Storj/storjnode#3]
While sending a files with test_network_sender.py i get the following exception. Complete output:

/home/storjnode/storjnode/bin# python test_network_sender.py [my address] [your address] test_network_sender.py
INFO storjnode.network.service 97: Starting network service!
INFO storjnode.network.service 125: Connecting to irc.quakenet.org:6667 as wTRUSteecubg.
INFO storjnode.network.service 128: Connection established!
INFO storjnode.network.service 148: Joined own channel #18X6bmEjAKfAhqega9xmBgJfy4rrJ3zxth
INFO storjnode.network.service 103: Network service started!
INFO storjnode.network.service 475: Queued 1287bytes to send 16ZcxFDdkVJR1P8GMNmWFyhS4EKrRMsWNG
INFO storjnode.network.service 313: Requesting connection to node 16ZcxFDdkVJR1P8GMNmWFyhS4EKrRMsWNG
INFO storjnode.network.service 334: Sending syn to node channel #16ZcxFDdkVJR1P8GMNmWFyhS4EKrRMsWNG
INFO storjnode.network.service 420: Received synack from 16ZcxFDdkVJR1P8GMNmWFyhS4EKrRMsWNG
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/usr/local/lib/python2.7/dist-packages/storjnode-0.0.2-py2.7.egg/storjnode/network/service.py", line 240, in _reactor_loop
    self._reactor.process_once(timeout=0.2)
  File "/usr/local/lib/python2.7/dist-packages/irc/client.py", line 259, in process_once
    self.process_data(i)
  File "/usr/local/lib/python2.7/dist-packages/irc/client.py", line 216, in process_data
    c.process_data()
  File "/usr/local/lib/python2.7/dist-packages/irc/client.py", line 582, in process_data
    self._process_line(line)
  File "/usr/local/lib/python2.7/dist-packages/irc/client.py", line 614, in _process_line
    handler(arguments, command, source, tags)
  File "/usr/local/lib/python2.7/dist-packages/irc/client.py", line 638, in _handle_message
    self._handle_event(event)
  File "/usr/local/lib/python2.7/dist-packages/irc/client.py", line 673, in _handle_event
    self.reactor._handle_event(self, event)
  File "/usr/local/lib/python2.7/dist-packages/irc/client.py", line 398, in _handle_event
    result = handler.callback(connection, event)
  File "/usr/local/lib/python2.7/dist-packages/storjnode-0.0.2-py2.7.egg/storjnode/network/service.py", line 416, in _on_ctcp
    self._on_synack(parsed, peer_address, peer_port)
  File "/usr/local/lib/python2.7/dist-packages/storjnode-0.0.2-py2.7.egg/storjnode/network/service.py", line 434, in _on_synack
    dcc.connect(peer_address, peer_port)
  File "/usr/local/lib/python2.7/dist-packages/irc/client.py", line 1041, in connect
    raise DCCConnectionError("Couldn't connect to socket: %s" % x)
DCCConnectionError: Couldn't connect to socket: [Errno 111] Connection refused

I would ignore the exception for now. The problem is that my terminal is freezed after that. I can't restart sending (in the same terminal)

I gues it is duplicate to https://github.com/Storj/storjnode/issues/2. For retest and documentation i open a second bug so we can't forget it.

**Comment by F483** [comment]
Fixed in https://github.com/Storj/storjnode/commit/78a1124fa895513e1072b966197059c5ea1dc92e
