### ISSUE TITLE
Failed to get transport info on startup.

### ISSUE THREAD

**Issue by F483** [Storj/storjnode#48]
How can the exception below occur if `bool([])` yields `False`?

```
======================================================================

ERROR: setUpClass (tests.network.node.TestNode)

----------------------------------------------------------------------

Traceback (most recent call last):

  File "tests/network/node.py", line 85, in setUpClass

    disable_data_transfer=False

  File "storjnode/network/node.py", line 127, in __init__

    store_config, passive_port, passive_bind, node_type, nat_type

  File "storjnode/network/node.py", line 178, in _setup_data_transfer_client

    wan_ip=result[0] if result else None

KeyError: 0

----------------------------------------------------------------------
```

**Comment by F483** [comment]
See e2f2e49cb2f499c06264aec8920da93875332434
