### ISSUE TITLE
Remove pygraphviz dependency

### ISSUE THREAD

**Issue by F483** [Storj/storjnode#50]
The pygraphviz dependency has been quite troublesome for building releases and development setup in general. 

The only use of pygraphviz has also reach its limitations as the network is now to large to render in any practical fashion.

```
Traceback (most recent call last):
  File "examples/network/map_network.py", line 69, in <module>
    print(storjnode.network.map.render(netmap, arguments["path"]))
  File "/home/f483/dev/storj/storjnode/env/local/lib/python2.7/site-packages/storjnode-0.0.20-py2.7.egg/storjnode/network/map.py", line 139, in render
    graph.draw(path, prog='circo')
  File "/home/f483/dev/storj/storjnode/env/local/lib/python2.7/site-packages/pygraphviz/agraph.py", line 1474, in draw
    data = self._run_prog(prog, args)
  File "/home/f483/dev/storj/storjnode/env/local/lib/python2.7/site-packages/pygraphviz/agraph.py", line 1335, in _run_prog
    raise IOError(b"".join(errors))
IOError: circo: failure to create cairo surface: out of memory
```

**Comment by F483** [comment]
Done
