### ISSUE TITLE
UnicodeDecodeError on dalnet

### ISSUE THREAD

**Issue by F483** [Storj/storjnode#7]
```
$ python storjnode/bin/test_network_receiver.py 
INFO root 47: WAITING FOR DATA AT 1JeLz8Ezjg76yDtFtxrPCgd2agYT8VreuT
INFO root 50: SAVING RECEIVED DATA AT /home/dataserv/.storjnode/test_network_receiver
INFO storjnode.network.service 128: Starting network service!
INFO storjnode.network.service 157: Connecting to irc.dal.net:6667 as SVImQBwYKWMh.
INFO storjnode.network.service 160: Connection established!
WARNING irc.buffer 109: 
Unknown encoding encountered. See 'Decoding Input'
in https://pypi.python.org/pypi/irc for details.

Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.4/threading.py", line 920, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.4/threading.py", line 868, in run
    self._target(*self._args, **self._kwargs)
  File "/home/dataserv/storjnode/env/lib/python3.4/site-packages/storjnode-0.0.2-py3.4.egg/storjnode/network/service.py", line 308, in _reactor_loop
    self._reactor.process_once(timeout=0.1)
  File "/home/dataserv/storjnode/env/lib/python3.4/site-packages/irc/client.py", line 259, in process_once
    self.process_data(i)
  File "/home/dataserv/storjnode/env/lib/python3.4/site-packages/irc/client.py", line 216, in process_data
    c.process_data()
  File "/home/dataserv/storjnode/env/lib/python3.4/site-packages/irc/client.py", line 579, in process_data
    for line in self.buffer:
  File "/home/dataserv/storjnode/env/lib/python3.4/site-packages/irc/buffer.py", line 102, in lines
    self.handle_exception()
  File "/home/dataserv/storjnode/env/lib/python3.4/site-packages/irc/buffer.py", line 100, in lines
    yield line.decode(self.encoding, self.errors)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xfc in position 122: invalid start byte
```

**Comment by F483** [comment]
outdated
