### ISSUE TITLE
QA on Test Group C client

### ISSUE THREAD

**Issue by super3** [Storj/storjnode#74]

**Comment by littleskunk** [comment]
Tested with autobin windows binary. Develop branch 29.01.2016

storjnode.exe --wallet xprv9s21ZrQH143K3m4QEqqF2hkQvTHczjeQbebVprErgQLF684MzDmbpMRDN4YdaTC9fxAFmw8sSKh6FqDXQYVZukmRgLhuYSbcTFca16Ut3EV stopserver
2016-01-29 19:07:28,188 INFO storjnode.network.node 118: Started storjnode on port 2827 with address 1Gw99SmF9C1J8jLHHUQum4MMXeuB9kz78V
Sorry stop server not supported just yet.

storjnode.exe --wallet xprv9s21ZrQH143K3m4QEqqF2hkQvTHczjeQbebVprErgQLF684MzDmbpMRDN4YdaTC9fxAFmw8sSKh6FqDXQYVZukmRgLhuYSbcTFca16Ut3EV msg_list
2016-01-29 19:25:32,628 INFO storjnode.network.node 118: Started storjnode on port 10962 with address 1Gw99SmF9C1J8jLHHUQum4MMXeuB9kz78V
Traceback (most recent call last):
  File "storjnode", line 22, in <module>
  File "apigen\apigen.pyo", line 254, in run
  File "apigen\apigen.pyo", line 58, in wrapper
  File "storjnode\api.pyo", line 308, in msg_list
NotImplementedError

storjnode.exe --wallet xprv9s21ZrQH143K3m4QEqqF2hkQvTHczjeQbebVprErgQLF684MzDmbpMRDN4YdaTC9fxAFmw8sSKh6FqDXQYVZukmRgLhuYSbcTFca16Ut3EV msg_send 1Gw99SmF9C1J8jLHHUQum4MMXeuB9kz78V testmessage
2016-01-29 19:28:52,864 INFO storjnode.network.node 118: Started storjnode on port 49948 with address 1Gw99SmF9C1J8jLHHUQum4MMXeuB9kz78V
Traceback (most recent call last):
  File "storjnode", line 22, in <module>
  File "apigen\apigen.pyo", line 254, in run
  File "apigen\apigen.pyo", line 58, in wrapper
  File "storjnode\api.pyo", line 303, in msg_send
NotImplementedError

storjnode.exe --wallet xprv9s21ZrQH143K3m4QEqqF2hkQvTHczjeQbebVprErgQLF684MzDmbpMRDN4YdaTC9fxAFmw8sSKh6FqDXQYVZukmRgLhuYSbcTFca16Ut3EV dht_dump
2016-01-29 19:30:22,351 INFO storjnode.network.node 118: Started storjnode on port 21669 with address 1Gw99SmF9C1J8jLHHUQum4MMXeuB9kz78V
Can't find any dump file. I put test=test befor.
