### ISSUE TITLE
storjnode py2exe binary not working

### ISSUE THREAD

**Issue by littleskunk** [Storj/storjnode#89]
storjnode.exe
Traceback (most recent call last):
  File "storjnode", line 12, in <module>
  File "zipextimporter.pyo", line 82, in load_module
  File "storjnode__init__.pyo", line 7, in <module>
  File "zipextimporter.pyo", line 82, in load_module
  File "storjnode\config__init__.pyo", line 5, in <module>
  File "zipextimporter.pyo", line 82, in load_module
  File "jsonschema__init__.pyo", line 18, in <module>
  File "zipextimporter.pyo", line 82, in load_module
  File "jsonschema\validators.pyo", line 163, in <module>
  File "jsonschema_utils.pyo", line 57, in load_schema
  File "pkgutil.pyo", line 591, in get_data
IOError: [Errno 0] Error: 'jsonschema\schemas\draft3.json'

**Comment by littleskunk** [comment]
Missing files:
site-packages\jsonschema\schemas\draft3.json
site-packages\jsonschema\schemas\draft4.json

**Comment by littleskunk** [comment]
Possible solution:
http://stackoverflow.com/questions/30942612/py2exe-not-recognizing-jsonschema
http://crazedmonkey.com/blog/python/pkg_resources-with-py2exe.html
